# Generated by Django 4.1.13 on 2024-02-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('createDate', models.DateField()),
                ('deadlineDate', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('projectManagerId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.IntegerField()),
                ('taskId', models.IntegerField()),
                ('projectName', models.CharField(max_length=100)),
                ('taskName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('startDate', models.DateField()),
                ('finishDate', models.DateField()),
                ('projectId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserOnProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('projectName', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserOnTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('taskName', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
