# Generated by Django 5.0.2 on 2024-02-21 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TaskManagerAPI", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserOnTask",
        ),
    ]
