# Generated by Django 5.0.1 on 2024-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
