# Generated by Django 5.0.1 on 2024-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(default=1),
        ),
    ]
